// Generated by @whisperr/wizard — do not edit by hand.
// Call bindWhisperr(client) once right after the Whisperr SDK is initialized;
// events tracked before binding are queued, never dropped.

type WhisperrPayloadValue = string | number | boolean;
type WhisperrClientLike = {
  track: (event: string, payload?: Record<string, WhisperrPayloadValue>) => unknown;
};

let boundClient: WhisperrClientLike | null = null;
const queued: Array<[string, Record<string, WhisperrPayloadValue> | undefined]> = [];

export function bindWhisperr(client: WhisperrClientLike): void {
  boundClient = client;
  while (queued.length > 0) {
    const [event, payload] = queued.shift()!;
    try { client.track(event, payload); } catch { /* analytics must never break the app */ }
  }
}

function emit(event: string, payload?: Record<string, WhisperrPayloadValue>): void {
  if (boundClient) {
    try { boundClient.track(event, payload); } catch { /* analytics must never break the app */ }
  } else {
    queued.push([event, payload]);
  }
}

export const WhisperrEvents = {
  /** order_id: order identifier */
  /** payment_status: confirmed payment status */
  paymentDeclined(payload: { orderId: WhisperrPayloadValue; paymentStatus: WhisperrPayloadValue }): void {
    const { orderId, paymentStatus } = payload;
    emit("payment_declined", { "order_id": orderId, "payment_status": paymentStatus });
  },
  /** account_creation_date: account creation date */
  /** skin_type: saved skin-type key when present */
  accountCreated(payload: { accountCreationDate: WhisperrPayloadValue; skinType: WhisperrPayloadValue }): void {
    const { accountCreationDate, skinType } = payload;
    emit("account_created", { "account_creation_date": accountCreationDate, "skin_type": skinType });
  },
  /** account_role: customer account role */
  /** account_creation_date: account creation date */
  /** skin_type: saved skin-type key when present */
  customerSignedIn(payload: { accountRole: WhisperrPayloadValue; accountCreationDate: WhisperrPayloadValue; skinType: WhisperrPayloadValue }): void {
    const { accountRole, accountCreationDate, skinType } = payload;
    emit("customer_signed_in", { "account_role": accountRole, "account_creation_date": accountCreationDate, "skin_type": skinType });
  },
  /** order_id: internal order identifier */
  /** payment_id: gateway payment identifier */
  /** gateway_order_status: verified gateway payment status */
  orderPaidConfirmed(payload: { orderId: WhisperrPayloadValue; paymentId: WhisperrPayloadValue; gatewayOrderStatus: WhisperrPayloadValue }): void {
    const { orderId, paymentId, gatewayOrderStatus } = payload;
    emit("order_paid_confirmed", { "order_id": orderId, "payment_id": paymentId, "gateway_order_status": gatewayOrderStatus });
  },
  /** items: basket product IDs, variant IDs, and quantities */
  /** value: basket subtotal */
  /** currency: basket currency */
  beginCheckout(payload: { items: WhisperrPayloadValue; value: WhisperrPayloadValue; currency: WhisperrPayloadValue }): void {
    const { items, value, currency } = payload;
    emit("begin_checkout", { "items": items, "value": value, "currency": currency });
  },
  /** currency: display currency */
  /** value: product price */
  /** items: viewed product ID, variant ID when selected, and price */
  viewItem(payload: { currency: WhisperrPayloadValue; value: WhisperrPayloadValue; items: WhisperrPayloadValue }): void {
    const { currency, value, items } = payload;
    emit("view_item", { "currency": currency, "value": value, "items": items });
  },
  /** category_slugs: selected category and subcategory identifiers */
  /** brand_slugs: selected brand identifiers */
  /** skin_type_keys: selected skin-type identifiers */
  /** price_min: selected minimum price */
  /** price_max: selected maximum price */
  /** sort: selected sort option */
  /** page: listing page number */
  /** result_total: total matching products */
  /** product_ids: shown product identifiers */
  catalogBrowsedWithResults(payload: { categorySlugs: WhisperrPayloadValue; brandSlugs: WhisperrPayloadValue; skinTypeKeys: WhisperrPayloadValue; priceMin: WhisperrPayloadValue; priceMax: WhisperrPayloadValue; sort: WhisperrPayloadValue; page: WhisperrPayloadValue; resultTotal: WhisperrPayloadValue; productIds: WhisperrPayloadValue }): void {
    const { categorySlugs, brandSlugs, skinTypeKeys, priceMin, priceMax, sort, page, resultTotal, productIds } = payload;
    emit("catalog_browsed_with_results", { "category_slugs": categorySlugs, "brand_slugs": brandSlugs, "skin_type_keys": skinTypeKeys, "price_min": priceMin, "price_max": priceMax, "sort": sort, "page": page, "result_total": resultTotal, "product_ids": productIds });
  },
  /** failure_category: categorized payment-form startup failure */
  /** cart_total: current checkout total */
  /** currency: checkout currency */
  /** courier_provider_id: selected courier identifier */
  paymentFormStartFailed(payload: { failureCategory: WhisperrPayloadValue; cartTotal: WhisperrPayloadValue; currency: WhisperrPayloadValue; courierProviderId: WhisperrPayloadValue }): void {
    const { failureCategory, cartTotal, currency, courierProviderId } = payload;
    emit("payment_form_start_failed", { "failure_category": failureCategory, "cart_total": cartTotal, "currency": currency, "courier_provider_id": courierProviderId });
  },
  /** confirmation_required: whether email confirmation is required */
  /** registration_outcome: registration completion outcome */
  accountAwaitingEmailConfirmation(payload: { confirmationRequired: WhisperrPayloadValue; registrationOutcome: WhisperrPayloadValue }): void {
    const { confirmationRequired, registrationOutcome } = payload;
    emit("account_awaiting_email_confirmation", { "confirmation_required": confirmationRequired, "registration_outcome": registrationOutcome });
  },
  /** reset_outcome: successful password-reset completion */
  passwordResetCompleted(payload: { resetOutcome: WhisperrPayloadValue }): void {
    const { resetOutcome } = payload;
    emit("password_reset_completed", { "reset_outcome": resetOutcome });
  },
  /** skin_type: saved skin-type key */
  skinProfileSaved(payload: { skinType: WhisperrPayloadValue }): void {
    const { skinType } = payload;
    emit("skin_profile_saved", { "skin_type": skinType });
  },
  /** product_id: added product identifier */
  /** variant_id: selected variant identifier when applicable */
  /** quantity: quantity added */
  /** value: added item value */
  /** currency: item currency */
  addToCart(payload: { productId: WhisperrPayloadValue; variantId: WhisperrPayloadValue; quantity: WhisperrPayloadValue; value: WhisperrPayloadValue; currency: WhisperrPayloadValue }): void {
    const { productId, variantId, quantity, value, currency } = payload;
    emit("add_to_cart", { "product_id": productId, "variant_id": variantId, "quantity": quantity, "value": value, "currency": currency });
  },
  /** product_id: saved product identifier */
  /** product_slug: saved product slug */
  /** brand_id: product brand identifier */
  /** category_slug: product category identifier */
  productAddedToWishlist(payload: { productId: WhisperrPayloadValue; productSlug: WhisperrPayloadValue; brandId: WhisperrPayloadValue; categorySlug: WhisperrPayloadValue }): void {
    const { productId, productSlug, brandId, categorySlug } = payload;
    emit("product_added_to_wishlist", { "product_id": productId, "product_slug": productSlug, "brand_id": brandId, "category_slug": categorySlug });
  },
  /** product_id: previously ordered product identifier */
  /** variant_id: previously ordered variant identifier when applicable */
  /** quantity: quantity re-added */
  repeatPurchaseItemReadded(payload: { productId: WhisperrPayloadValue; variantId: WhisperrPayloadValue; quantity: WhisperrPayloadValue }): void {
    const { productId, variantId, quantity } = payload;
    emit("repeat_purchase_item_readded", { "product_id": productId, "variant_id": variantId, "quantity": quantity });
  },
  /** product_result_count: number of matching products shown */
  /** category_result_count: number of matching categories shown */
  /** brand_result_count: number of matching brands shown */
  /** product_ids: stable identifiers of matching products shown */
  /** category_slugs: stable slugs of matching categories shown */
  /** brand_slugs: stable slugs of matching brands shown */
  quickSearchResultsViewed(payload: { productResultCount: WhisperrPayloadValue; categoryResultCount: WhisperrPayloadValue; brandResultCount: WhisperrPayloadValue; productIds: WhisperrPayloadValue; categorySlugs: WhisperrPayloadValue; brandSlugs: WhisperrPayloadValue }): void {
    const { productResultCount, categoryResultCount, brandResultCount, productIds, categorySlugs, brandSlugs } = payload;
    emit("quick_search_results_viewed", { "product_result_count": productResultCount, "category_result_count": categoryResultCount, "brand_result_count": brandResultCount, "product_ids": productIds, "category_slugs": categorySlugs, "brand_slugs": brandSlugs });
  },
  /** order_id: non-PII order identifier */
  /** courier_shipment_id: courier shipment identifier */
  /** courier_status: confirmed courier shipment status */
  /** order_status: mapped fulfilment status */
  courierShipmentBooked(payload: { orderId: WhisperrPayloadValue; courierShipmentId: WhisperrPayloadValue; courierStatus: WhisperrPayloadValue; orderStatus: WhisperrPayloadValue }): void {
    const { orderId, courierShipmentId, courierStatus, orderStatus } = payload;
    emit("courier_shipment_booked", { "order_id": orderId, "courier_shipment_id": courierShipmentId, "courier_status": courierStatus, "order_status": orderStatus });
  },
  /** order_id: non-PII order identifier */
  /** failure_category: stable courier booking failure category */
  courierBookingFailedAfterPayment(payload: { orderId: WhisperrPayloadValue; failureCategory: WhisperrPayloadValue }): void {
    const { orderId, failureCategory } = payload;
    emit("courier_booking_failed_after_payment", { "order_id": orderId, "failure_category": failureCategory });
  },
  /** order_id: non-PII order identifier */
  /** courier_shipment_id: courier shipment identifier */
  /** courier_status: courier-reported delivered status */
  /** order_status: mapped fulfilment status */
  orderDelivered(payload: { orderId: WhisperrPayloadValue; courierShipmentId: WhisperrPayloadValue; courierStatus: WhisperrPayloadValue; orderStatus: WhisperrPayloadValue }): void {
    const { orderId, courierShipmentId, courierStatus, orderStatus } = payload;
    emit("order_delivered", { "order_id": orderId, "courier_shipment_id": courierShipmentId, "courier_status": courierStatus, "order_status": orderStatus });
  },
  /** order_id: non-PII order identifier */
  /** courier_shipment_id: courier shipment identifier */
  /** delivery_outcome: delivery_failed or cancelled */
  /** courier_status: courier-reported shipment status */
  deliveryFailedOrCancelled(payload: { orderId: WhisperrPayloadValue; courierShipmentId: WhisperrPayloadValue; deliveryOutcome: WhisperrPayloadValue; courierStatus: WhisperrPayloadValue }): void {
    const { orderId, courierShipmentId, deliveryOutcome, courierStatus } = payload;
    emit("delivery_failed_or_cancelled", { "order_id": orderId, "courier_shipment_id": courierShipmentId, "delivery_outcome": deliveryOutcome, "courier_status": courierStatus });
  },
  /** category_slugs: selected category and subcategory identifiers */
  /** brand_slugs: selected brand identifiers */
  /** skin_type_keys: selected skin-type identifiers */
  /** price_min: selected minimum price */
  /** price_max: selected maximum price */
  /** sort: selected sort option */
  catalogFiltersReturnNoResults(payload: { categorySlugs: WhisperrPayloadValue; brandSlugs: WhisperrPayloadValue; skinTypeKeys: WhisperrPayloadValue; priceMin: WhisperrPayloadValue; priceMax: WhisperrPayloadValue; sort: WhisperrPayloadValue }): void {
    const { categorySlugs, brandSlugs, skinTypeKeys, priceMin, priceMax, sort } = payload;
    emit("catalog_filters_return_no_results", { "category_slugs": categorySlugs, "brand_slugs": brandSlugs, "skin_type_keys": skinTypeKeys, "price_min": priceMin, "price_max": priceMax, "sort": sort });
  },
  /** courier_provider_ids: quoted courier provider identifiers */
  /** courier_names: quoted courier names */
  /** fees: quoted delivery fees */
  /** eta_minutes: quoted delivery estimates */
  /** used_fallback_fee: whether a configured fallback fee was used */
  deliveryOptionsReturned(payload: { courierProviderIds: WhisperrPayloadValue; courierNames: WhisperrPayloadValue; fees: WhisperrPayloadValue; etaMinutes: WhisperrPayloadValue; usedFallbackFee: WhisperrPayloadValue }): void {
    const { courierProviderIds, courierNames, fees, etaMinutes, usedFallbackFee } = payload;
    emit("delivery_options_returned", { "courier_provider_ids": courierProviderIds, "courier_names": courierNames, "fees": fees, "eta_minutes": etaMinutes, "used_fallback_fee": usedFallbackFee });
  },
  /** delivery_error_category: address lookup or no-courier outcome category */
  /** courier_service_configured: whether courier quoting was configured */
  /** quote_count: number of returned courier quotes */
  /** fallback_fee_available: whether a fallback delivery fee was available */
  deliveryAddressNotServiceable(payload: { deliveryErrorCategory: WhisperrPayloadValue; courierServiceConfigured: WhisperrPayloadValue; quoteCount: WhisperrPayloadValue; fallbackFeeAvailable: WhisperrPayloadValue }): void {
    const { deliveryErrorCategory, courierServiceConfigured, quoteCount, fallbackFeeAvailable } = payload;
    emit("delivery_address_not_serviceable", { "delivery_error_category": deliveryErrorCategory, "courier_service_configured": courierServiceConfigured, "quote_count": quoteCount, "fallback_fee_available": fallbackFeeAvailable });
  },
  /** order_id: order identifier */
  /** payment_status: latest payment status */
  /** polling_attempts: number of completed status checks */
  paymentConfirmationDelayed(payload: { orderId: WhisperrPayloadValue; paymentStatus: WhisperrPayloadValue; pollingAttempts: WhisperrPayloadValue }): void {
    const { orderId, paymentStatus, pollingAttempts } = payload;
    emit("payment_confirmation_delayed", { "order_id": orderId, "payment_status": paymentStatus, "polling_attempts": pollingAttempts });
  },
  /** order_id: order identifier */
  /** order_status: current fulfilment status */
  /** payment_status: current payment status */
  /** item_count: number of ordered items */
  /** total: order total */
  /** courier_provider: assigned courier provider */
  guestOrderTracked(payload: { orderId: WhisperrPayloadValue; orderStatus: WhisperrPayloadValue; paymentStatus: WhisperrPayloadValue; itemCount: WhisperrPayloadValue; total: WhisperrPayloadValue; courierProvider: WhisperrPayloadValue }): void {
    const { orderId, orderStatus, paymentStatus, itemCount, total, courierProvider } = payload;
    emit("guest_order_tracked", { "order_id": orderId, "order_status": orderStatus, "payment_status": paymentStatus, "item_count": itemCount, "total": total, "courier_provider": courierProvider });
  },
  /** is_default: whether this became the default address */
  /** country: saved delivery country */
  shippingAddressSaved(payload: { isDefault: WhisperrPayloadValue; country: WhisperrPayloadValue }): void {
    const { isDefault, country } = payload;
    emit("shipping_address_saved", { "is_default": isDefault, "country": country });
  },
  /** product_id: product identifier */
  /** variant_id: selected variant identifier when applicable */
  /** stock_outcome: out_of_stock or quantity_capped */
  /** requested_quantity: requested quantity when capped */
  /** available_inventory: available stock quantity */
  addToCartBlockedByStock(payload: { productId: WhisperrPayloadValue; variantId: WhisperrPayloadValue; stockOutcome: WhisperrPayloadValue; requestedQuantity: WhisperrPayloadValue; availableInventory: WhisperrPayloadValue }): void {
    const { productId, variantId, stockOutcome, requestedQuantity, availableInventory } = payload;
    emit("add_to_cart_blocked_by_stock", { "product_id": productId, "variant_id": variantId, "stock_outcome": stockOutcome, "requested_quantity": requestedQuantity, "available_inventory": availableInventory });
  },
  /** product_id: product identifier */
  /** variant_id: selected variant identifier */
  /** variant_name: variant label */
  /** price: selected variant price */
  /** compare_at_price: selected variant comparison price */
  /** available_inventory: selected variant inventory */
  productVariantSelected(payload: { productId: WhisperrPayloadValue; variantId: WhisperrPayloadValue; variantName: WhisperrPayloadValue; price: WhisperrPayloadValue; compareAtPrice: WhisperrPayloadValue; availableInventory: WhisperrPayloadValue }): void {
    const { productId, variantId, variantName, price, compareAtPrice, availableInventory } = payload;
    emit("product_variant_selected", { "product_id": productId, "variant_id": variantId, "variant_name": variantName, "price": price, "compare_at_price": compareAtPrice, "available_inventory": availableInventory });
  },
  /** product_id: moved product identifier */
  /** product_slug: moved product slug */
  wishlistItemSavedForLater(payload: { productId: WhisperrPayloadValue; productSlug: WhisperrPayloadValue }): void {
    const { productId, productSlug } = payload;
    emit("wishlist_item_saved_for_later", { "product_id": productId, "product_slug": productSlug });
  },
  /** cart_line_id: removed cart-line identifier */
  /** product_id: removed product identifier */
  /** variant_id: removed variant identifier when applicable */
  /** quantity: quantity removed */
  cartItemRemoved(payload: { cartLineId: WhisperrPayloadValue; productId: WhisperrPayloadValue; variantId: WhisperrPayloadValue; quantity: WhisperrPayloadValue }): void {
    const { cartLineId, productId, variantId, quantity } = payload;
    emit("cart_item_removed", { "cart_line_id": cartLineId, "product_id": productId, "variant_id": variantId, "quantity": quantity });
  },
  /** cart_line_count: number of basket lines */
  /** product_ids: basket product identifiers */
  /** variant_ids: basket variant identifiers */
  /** subtotal: basket subtotal */
  /** shipping: current shipping amount */
  /** tax: current tax amount */
  /** total: basket total */
  /** currency: basket currency */
  checkoutStarted(payload: { cartLineCount: WhisperrPayloadValue; productIds: WhisperrPayloadValue; variantIds: WhisperrPayloadValue; subtotal: WhisperrPayloadValue; shipping: WhisperrPayloadValue; tax: WhisperrPayloadValue; total: WhisperrPayloadValue; currency: WhisperrPayloadValue }): void {
    const { cartLineCount, productIds, variantIds, subtotal, shipping, tax, total, currency } = payload;
    emit("checkout_started", { "cart_line_count": cartLineCount, "product_ids": productIds, "variant_ids": variantIds, "subtotal": subtotal, "shipping": shipping, "tax": tax, "total": total, "currency": currency });
  },
  /** courier_provider_id: selected courier provider identifier */
  /** courier_name: selected courier name */
  /** fee: selected delivery fee */
  /** eta_minutes: selected delivery estimate */
  courierSelected(payload: { courierProviderId: WhisperrPayloadValue; courierName: WhisperrPayloadValue; fee: WhisperrPayloadValue; etaMinutes: WhisperrPayloadValue }): void {
    const { courierProviderId, courierName, fee, etaMinutes } = payload;
    emit("courier_selected", { "courier_provider_id": courierProviderId, "courier_name": courierName, "fee": fee, "eta_minutes": etaMinutes });
  },
  /** lookup_outcome: order_not_found */
  guestOrderLookupFailed(payload: { lookupOutcome: WhisperrPayloadValue }): void {
    const { lookupOutcome } = payload;
    emit("guest_order_lookup_failed", { "lookup_outcome": lookupOutcome });
  },
  /** order_id: order identifier */
  /** order_status: current fulfilment status */
  /** payment_status: current payment status */
  /** product_ids: ordered product identifiers */
  /** variant_ids: ordered variant identifiers */
  /** total: order total */
  /** courier_provider: assigned courier provider */
  orderDetailViewed(payload: { orderId: WhisperrPayloadValue; orderStatus: WhisperrPayloadValue; paymentStatus: WhisperrPayloadValue; productIds: WhisperrPayloadValue; variantIds: WhisperrPayloadValue; total: WhisperrPayloadValue; courierProvider: WhisperrPayloadValue }): void {
    const { orderId, orderStatus, paymentStatus, productIds, variantIds, total, courierProvider } = payload;
    emit("order_detail_viewed", { "order_id": orderId, "order_status": orderStatus, "payment_status": paymentStatus, "product_ids": productIds, "variant_ids": variantIds, "total": total, "courier_provider": courierProvider });
  },
  /** product_id: Displayed product identifier */
  /** product_slug: Displayed product slug */
  /** variant_ids: Available variant identifiers */
  /** price: Displayed product price */
  /** inventory_quantity: Displayed available inventory */
  productQuickViewOpened(payload: { productId: WhisperrPayloadValue; productSlug: WhisperrPayloadValue; variantIds: WhisperrPayloadValue; price: WhisperrPayloadValue; inventoryQuantity: WhisperrPayloadValue }): void {
    const { productId, productSlug, variantIds, price, inventoryQuantity } = payload;
    emit("product_quick_view_opened", { "product_id": productId, "product_slug": productSlug, "variant_ids": variantIds, "price": price, "inventory_quantity": inventoryQuantity });
  },
  /** product_id: Removed product identifier */
  /** product_slug: Removed product slug */
  /** brand_id: Product brand identifier */
  /** brand_slug: Product brand slug */
  /** category_slug: Product category */
  /** price: Current product price */
  /** inventory_quantity: Current product inventory */
  productRemovedFromWishlist(payload: { productId: WhisperrPayloadValue; productSlug: WhisperrPayloadValue; brandId: WhisperrPayloadValue; brandSlug: WhisperrPayloadValue; categorySlug: WhisperrPayloadValue; price: WhisperrPayloadValue; inventoryQuantity: WhisperrPayloadValue }): void {
    const { productId, productSlug, brandId, brandSlug, categorySlug, price, inventoryQuantity } = payload;
    emit("product_removed_from_wishlist", { "product_id": productId, "product_slug": productSlug, "brand_id": brandId, "brand_slug": brandSlug, "category_slug": categorySlug, "price": price, "inventory_quantity": inventoryQuantity });
  },
  passwordResetRequested(): void {
    emit("password_reset_requested");
  },
  searchReturnedNoResults(): void {
    emit("search_returned_no_results");
  },
  /** product_id: stable product identifier */
  /** product_slug: stable product slug */
  /** product_price: listed product price at selection */
  searchProductSelected(payload: { productId: WhisperrPayloadValue; productSlug: WhisperrPayloadValue; productPrice: WhisperrPayloadValue }): void {
    const { productId, productSlug, productPrice } = payload;
    emit("search_product_selected", { "product_id": productId, "product_slug": productSlug, "product_price": productPrice });
  },
  /** block_type: stable category for changed or unavailable courier quote */
  /** quote_source: stored delivery quote source */
  /** stored_fee: previous delivery fee */
  /** live_fee: rechecked delivery fee */
  checkoutBlockedByStockOrReprice(payload: { blockType: WhisperrPayloadValue; quoteSource: WhisperrPayloadValue; storedFee: WhisperrPayloadValue; liveFee: WhisperrPayloadValue }): void {
    const { blockType, quoteSource, storedFee, liveFee } = payload;
    emit("checkout_blocked_by_stock_or_reprice", { "block_type": blockType, "quote_source": quoteSource, "stored_fee": storedFee, "live_fee": liveFee });
  },
  /** order_id: non-PII order identifier */
  /** courier_shipment_id: courier shipment identifier */
  /** courier_status: courier-reported shipment status */
  /** order_status: mapped fulfilment status */
  orderShipped(payload: { orderId: WhisperrPayloadValue; courierShipmentId: WhisperrPayloadValue; courierStatus: WhisperrPayloadValue; orderStatus: WhisperrPayloadValue }): void {
    const { orderId, courierShipmentId, courierStatus, orderStatus } = payload;
    emit("order_shipped", { "order_id": orderId, "courier_shipment_id": courierShipmentId, "courier_status": courierStatus, "order_status": orderStatus });
  },
  /** product_id: stable product identifier */
  savedForLaterItemRemoved(payload: { productId: WhisperrPayloadValue }): void {
    const { productId } = payload;
    emit("saved_for_later_item_removed", { "product_id": productId });
  },
  /** cart_item_id: stable cart line identifier */
  /** product_id: stable product identifier */
  /** variant_id: stable selected variant identifier when applicable */
  /** requested_quantity: quantity requested by the shopper */
  /** stored_quantity: quantity retained in the cart after stock limiting */
  /** available_quantity: available stock at the time of the change */
  cartItemQuantityChanged(payload: { cartItemId: WhisperrPayloadValue; productId: WhisperrPayloadValue; variantId: WhisperrPayloadValue; requestedQuantity: WhisperrPayloadValue; storedQuantity: WhisperrPayloadValue; availableQuantity: WhisperrPayloadValue }): void {
    const { cartItemId, productId, variantId, requestedQuantity, storedQuantity, availableQuantity } = payload;
    emit("cart_item_quantity_changed", { "cart_item_id": cartItemId, "product_id": productId, "variant_id": variantId, "requested_quantity": requestedQuantity, "stored_quantity": storedQuantity, "available_quantity": availableQuantity });
  },
  /** order_id: internal order identifier */
  /** order_number: store order reference */
  /** block_reason: stable checkout block category such as stock shortage */
  checkoutBlockedByStockShort(payload: { orderId: WhisperrPayloadValue; orderNumber: WhisperrPayloadValue; blockReason: WhisperrPayloadValue }): void {
    const { orderId, orderNumber, blockReason } = payload;
    emit("checkout_blocked_by_stock_short", { "order_id": orderId, "order_number": orderNumber, "block_reason": blockReason });
  },
};
